infinyon/fluvio-docs

.github/workflows/ci.yml, DOC-WRITERS.md, Justfile, README.md
Add external internal link checker to workflow (non-blocking atm)
Add sample run tasks in Justfile
Doc to url mapping notes
=> add: justfile w/ link check tooling (experimental)

news/this-week-in-fluvio-0058.md, news/this-week-in-fluvio-0059.md, news/this-week-in-fluvio-0060.md, news/this-week-in-fluvio-0061.md, news/this-week-in-fluvio-0062.md, news/this-week-in-fluvio-0063.md, news/this-week-in-fluvio-0064.md, src/components/Landing/components/Hero.tsx
Updated links on TWIF58 -TWIF64
=> update links twif58-64

docs/connectors/developers/overview.mdx, docs/connectors/troubleshooting.mdx
- **Add fluvio install rust link**
- **Add cdk build troubleshooting topic**
=> add: cdk cross build troubleshooting

docs/fluvio/quickstart.mdx, versioned_docs/version-0.11.11/connectors/developers/overview.mdx, versioned_docs/version-0.11.11/connectors/troubleshooting.mdx, versioned_docs/version-0.11.11/fluvio/quickstart.mdx, versioned_docs/version-0.11.11/fluvio/tutorials/config/http-cat-fact-basic.yaml, versioned_docs/version-0.11.11/fluvio/tutorials/config/http-cat-fact-transform.yaml, versioned_docs/version-0.11.11/fluvio/tutorials/config/sql-cat-fact.yaml, versioned_docs/version-0.11.11/fluvio/tutorials/output-sql.mdx, versioned_docs/version-0.11.11/fluvio/tutorials/source-http-basic.mdx, versioned_docs/version-0.11.11/fluvio/tutorials/source-http-transformation.mdx
- **fix fluvio/quickstart**
- **resync versioned_docs**
=> fix: fluvio/quickstart, sync w/ versioned_docs

sdf/compositions/overview.mdx, sdf/compositions/sdf-package-yaml.mdx, sdf/concepts/services/state.mdx, sdf/quickstart.mdx, sdf/tutorials/filter_operator.mdx, versioned_docs/version-0.11.11/_embeds/cmds/cdk-deploy-start-http-source-quotes.bash, versioned_docs/version-0.11.11/_embeds/cmds/cdk-deploy-start-http-source-string-quotes.bash, versioned_docs/version-0.11.11/_embeds/cmds/hub-sm-download-jolt.bash, versioned_docs/version-0.11.11/_embeds/cmds/hub-sm-list-jolt.bash, versioned_docs/version-0.11.11/_embeds/cmds/sm-list-jolt.bash, versioned_docs/version-0.11.11/_embeds/connectors/http-cat-fact-basic.yaml, versioned_docs/version-0.11.11/_embeds/connectors/http-source-quotes-transform.yaml, versioned_docs/version-0.11.11/_embeds/connectors/http-source-quotes.yaml, versioned_docs/version-0.11.11/_embeds/transforms/infinyon-jolt.yaml, versioned_docs/version-0.11.11/cloud/overview.mdx, versioned_docs/version-0.11.11/cloud/quickstart.mdx, versioned_docs/version-0.11.11/connectors/how-to/run-local.mdx, versioned_docs/version-0.11.11/fluvio/quickstart.mdx
- **fix remaining links**
- **resync ver docs**
=> fix: broken links

docs/hub/connectors/inbound/mqtt.mdx, docs/smartmodules/features/deduplication.mdx, docs/smartmodules/features/lookback.mdx
Updated said files:
mqtt.mdx
- inclusion of downloading the mqtt ipkg
deduplication.mdx
lookback.mdx
- updated smdk generation output
- fixed topic name syntax
=> documentation update

docs/connectors/configuration.mdx
The values in the ref are too big and this being copy/paste.   Just reduced to min
=> remove unnecessary config

versioned_docs/version-0.11.11/fluvio/apis/python/example.mdx
=> doc: typo fix of python smartmodule example

docusaurus.config.ts
Search bar items now renders the path to the article
https://github.com/user-attachments/assets/3727ae26-30f3-43f2-9c36-b010026890db
=> feat: renders doc path in search list

package-lock.json, package.json
Fixes issue https://github.com/easyops-cn/docusaurus-search-local/issues/364 by applying
patch on https://github.com/easyops-cn/docusaurus-search-local/commit/69378e67944ca3abd15e179621b5ca53903eecce by upgrading to https://github.com/easyops-cn/docusaurus-search-local/releases/tag/v0.44.5.
=> fix: `docusaurus-search-local` by upgrading to `v0.44.5`

docusaurus.config.ts, src/theme/NavbarItem/ComponentTypes.tsx, src/theme/NavbarItem/GitHubStars/index.tsx, src/theme/NavbarItem/GitHubStars/styles.module.css
This reverts commit b82847c6b0fc55898dce732bb84ca7d8d4644eb0 w/ some adjustment
https://github.com/infinyon/fluvio-docs/issues/254
=> readd "feat: provide gh stars counter on hero"

sdf/cli/deploy.mdx, sdf/cli/log.mdx, sdf/cli/run.mdx, sdf/composition/hub.mdx, sdf/composition/quickstart.mdx, sdf/concepts/environment-variables.mdx, sdf/deployment.mdx, sdf/how-to/dependencies.mdx, sdf/how-to/filter_map_operator.mdx, sdf/how-to/filter_operator.mdx, sdf/how-to/flat_map_operator.mdx, sdf/how-to/key_value-chained.mdx, sdf/how-to/key_value-input.mdx, sdf/how-to/key_value-output.mdx, sdf/how-to/map_operator.mdx, sdf/how-to/merge.mdx, sdf/how-to/split_filter_map_operator.mdx, sdf/how-to/split_filter_operator.mdx, sdf/how-to/state_example.mdx, sdf/how-to/state_example_arrow_row.mdx, sdf/how-to/tumbling_window.mdx, sdf/quickstart.mdx, sdf/whatsnew.mdx
Updated SDF docs for beta2.
- updated deployment
- added cli `deploy`
- remove ephemeral 
- added what's new
=> sdf beta2 changes

sdf/cli/index.mdx, sdf/composition/quickstart.mdx, sdf/quickstart.mdx, sdf/whatsnew.mdx
updated what's new section
update `beta1.1` -> beta2
=> beta2 updates

docs/fluvio/apis/overview.mdx, docs/fluvio/concepts/batching.mdx
Related: https://github.com/infinyon/fluvio/pull/4195
=> chore: docs about max_request_size

sdf/whatsnew.mdx, sdf_versioned_docs/version-sdf-beta5/whatsnew.mdx
update title to refer the right version
=> chore: update whatsnew title

docs/_embeds/connectors/docker/Dockerfile
Dockerfile was changed to a two step build, to reduce the final container image size
=> Update Dockerfile for connectors

sdf/deployment.mdx
Refines the "Managing Dataflows" section. 
Mostly minor adjustments to phrasing and changes to make it read like general documentation instead of a concrete tutorial.
=> Proof controlling dataflows section

sdf/_embeds/dataflows/word-length.yaml, sdf/quickstart.mdx
- Re-phrases a few things
- Re names some of the dataflow.yaml objects 
- Adds a paragraph to very briefly explain the contents of the dataflow.yaml
=> Revise SDF Quickstart

package-lock.json
Perform `npm audit fix` to perform patches on packages with security improvements.
=> fix: run audit fixes from npm

src/components/DocSidebarFooter.tsx, src/theme/DocSidebar/Desktop/CollapseButton/index.tsx, src/theme/DocSidebar/Desktop/CollapseButton/styles.module.css, src/theme/DocSidebar/Desktop/Content/index.tsx, src/theme/DocSidebar/Desktop/Content/styles.module.css, src/theme/DocSidebar/Desktop/index.tsx, src/theme/DocSidebar/Desktop/styles.module.css, src/theme/DocSidebar/Mobile/index.tsx, src/theme/DocSidebar/index.tsx
- **fix: run audit fixes from npm**
- **feat: provide docsidebar**
- **feat: provide footer with product and version**
=> feat: docs sidebar footer with version and product name

versioned_docs/version-0.17.0/fluvio/troubleshooting.mdx
=> add docs for spu port conflicts #4492

docs/fluvio/troubleshooting.mdx
Added changes to trouble shooting root folder. Now it will be visible on latest build.
=> Merging changes to folder at the root Fixed #394

versioned_docs/version-0.17.2/hub/overview.mdx
Fixed small typo in hub overview page
=> Fix typo in overview.mdx

docs/fluvio/installation/docker.mdx, sdf/SDF_VERSION, sdf/_embeds/install-sdf.bash, sdf/concepts/window-processing.mdx, sdf/faq.mdx, sdf/index.mdx, sdf/whatsnew.mdx, versioned_docs/version-0.11.11/fluvio/installation/docker.mdx, versioned_docs/version-0.11.12/fluvio/installation/docker.mdx, versioned_docs/version-0.12.0/fluvio/installation/docker.mdx, versioned_docs/version-0.13.0/fluvio/installation/docker.mdx, versioned_docs/version-0.14.0/fluvio/installation/docker.mdx, versioned_docs/version-0.14.1/fluvio/installation/docker.mdx, versioned_docs/version-0.15.0/fluvio/installation/docker.mdx, versioned_docs/version-0.15.1/fluvio/installation/docker.mdx, versioned_docs/version-0.16.1/fluvio/installation/docker.mdx, versioned_docs/version-0.17.0/fluvio/installation/docker.mdx
=> Sdf beta10 changes
